name: Quality Check

on:
  push:
    branches:
      - "*"
      - "**"
      - "*/*"
      - "!master"

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18

      - name: Install packages
        run: npm ci

      - name: Audit report
        run: npm audit

      - name: Run lint check
        run: npm run lint
